### ISSUE TITLE
logic error

### ISSUE THREAD

**Issue by zaddan** [bu-icsg/dana#24]
I get the following error while trying to ./build.sh:

Configuring project riscv-isa-sim
Building project riscv-isa-sim
../riscv/extension.cc: In member function ‘void extension_t::raise_interrupt()’:
../riscv/extension.cc:23:9: error: ‘logic_error’ is not a member of ‘std’
gmake: **\* [extension.o] Error 1
gmake: **\* Waiting for unfinished jobs....
../riscv/interactive.cc: In member function ‘reg_t sim_t::get_reg(const std::vectorstd::basic_string<char >&)’:
../riscv/interactive.cc:181:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../riscv/interactive.cc:192:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
../spike_main/disasm.cc: In constructor ‘disassembler_t::disassembler_t()’:
../spike_main/disasm.cc:253:1: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without

**Comment by seldridge** [comment]
Technically this is an issue with [riscv-isa-sim](https://github.com/riscv/riscv-isa-sim) or, more generally, [riscv-tools](https://github.com/riscv/riscv-tools). Can you verify that you've cleared the dependencies needed for riscv-tools and that you have GCC > 4.8 (i.e., that you've taken care of everything here: https://github.com/riscv/riscv-tools#quickstart)?

**Comment by seldridge** [comment]
I think this issue is superseded by #25.
