### ISSUE TITLE
pls help where to buy fpga 

### ISSUE THREAD

**Issue by Sandy4321** [bu-icsg/dana#40]
in order try it needs fpga toolkit , but where ti buy?

**Comment by seldridge** [comment]
You can technically use anything here without an FPGA, but it will be slow as you're doing a software simulation of hardware (see: https://github.com/bu-icsg/xfiles-dana#-simulation). 

If you do want to use an FPGA, the advised FPGAs are those compatible with https://github.com/ucb-bar/fpga-zynq, sepcifically:
  * [Zedboard](http://zedboard.org/product/zedboard)
  * [ZC706](https://www.xilinx.com/products/boards-and-kits/ek-z7-zc706-g.html)

Technically, fpga-zynq can target a [Zybo](http://store.digilentinc.com/zybo-zynq-7000-arm-fpga-soc-trainer-board/), but that can only fit a very small rocket configuration and doesn't (last I checked) have room for any accelerators or an FPU.
