### ISSUE TITLE
Error in building emulator

### ISSUE THREAD

**Issue by phthinh** [bu-icsg/dana#47]
It has an error when I built the emulator according to the guide as follow:
# Build an emulator
cd $fpga_zynq_dir/rocket-chip/emulator
make ROCKETCHIP_ADDONS=dana CONFIG=XFilesDanaCPPConfig

It seems that there is no defined XFilesDanaCPPConfig CONFIG.
I think it should be CONFIG=DanaEmulatorConfig, isn't it?

**Comment by seldridge** [comment]
You're exactly right with the fix. Thanks for pointing out what the solution should be! This is now correctly specified in the short version of the top level README.md.
